name: Sync Garmin CN to Garmin Global

on:
  workflow_dispatch:
  schedule:
    #  每6小时检查一次
    - cron: "0 */6 * * *"
    - cron: "*/20 1-2 * * *"
    - cron: "*/30 13-15 * * *"
  push:
    branches:
      - main

env:
  # please change to your own config.
  RQ_COOKIE: ${{ secrets.RQ_COOKIE }}
  RQ_CSRF_TOKEN: ${{ secrets.RQ_CSRF_TOKEN }}
  RQ_USERID: ${{ secrets.RQ_USERID }}
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_API_CLIENT_EMAIL: ${{ secrets.GOOGLE_API_CLIENT_EMAIL }}
  GOOGLE_API_PRIVATE_KEY: ${{ secrets.GOOGLE_API_PRIVATE_KEY }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sync Garmin CN to Garmin Global
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
      # - run: yarn sync_cn
      - name: Run yarn sync_cn and save the output
        id: Run_sync_cn
        run: |
          # 运行yarn sync_cn任务
          result=$(yarn sync_cn) 
          echo "$result"
          echo "MAIL_HEAD=''" >> $GITHUB_ENV
          echo "MAIL_BODY=''" >> $GITHUB_ENV
          echo "HAS_NEW_ACTIVITY=false" >> $GITHUB_ENV
          aaa="location: 北京, 海淀}同步从这里开始同步开始时间: 2024-06-03 19:39:25没有要同步的活动内容, 最近的活动:  【 海淀区 公路越野 】, 开始于: 【 2024-06-03 08:22:02 】"
          # 从环境变量中获取字符串
          # 使用 sed 将自定义分隔符替换为逗号
          modified_string1=$(echo "$result" | sed ':a;N;$!ba;s/\n/\\n/g')
          modified_string2=$(echo "$modified_string1" | sed 's/xxd/\n/g')
          IFS=$'\n' read -r -a array <<< "$modified_string2"

          echo "$result" | awk '/同步从这里开始/ {flag=1; next} flag'
          
          echo "=========github workflow debug START========="
          # echo "$aaa"
          # echo "----"
          # echo "${array[0]}"
          # echo "${array[1]}"
          # echo "${array[2]}"
          # echo "${array[3]}"
          # 使用正则表达式提取区间内的字符串
          extracted=$(echo "$result" | grep -oP '【\K[^】]+')
          echo "$extracted"
          if [[ "$result" == *"没有要同步的活动内容"* ]]; then
            echo "没有要同步的活动内容"
            echo "MAIL_HEAD=没有要同步的活动内容" >> $GITHUB_ENV
            # echo "::set-output name=HAS_NEW_ACTIVITY::false"
            echo "HAS_NEW_ACTIVITY=false" >> $GITHUB_ENV
          else
            echo "有新同步的活动内容"
            echo "$extracted"
            echo "MAIL_HEAD<<EOF" >> $GITHUB_ENV
            echo "$extracted" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV  
            # echo "::set-output name=HAS_NEW_ACTIVITY::true"
            echo "HAS_NEW_ACTIVITY=true" >> $GITHUB_ENV
          fi
          echo "MAIL_BODY<<EOF" >> $GITHUB_ENV
          echo "$result" >> $GITHUB_ENV
          # echo "${array[1]}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "MAIL_BODY ---"
          echo "$MAIL_BODY"
          echo "=========github workflow debug END========="
        timeout-minutes: 5
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Save Garmin Session
      - name: 'Send mail'
        if: env.HAS_NEW_ACTIVITY == 'true'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{env.MAIL_HEAD}}-Github
          # html_body: ${{env.MAIL_BODY}}
          body: ${{ env.MAIL_BODY }}
          to: 925276588@qq.com
          from: Garmin同步状态
