name: Sync Garmin CN to Garmin Global

on:
  workflow_dispatch:
  schedule:
    #  每6小时检查一次
    - cron: "0 */6 * * *"
    - cron: "*/20 1-2 * * *"
    - cron: "*/30 13-15 * * *"
  push:
    branches:
      - main

env:
  # please change to your own config.
  RQ_COOKIE: ${{ secrets.RQ_COOKIE }}
  RQ_CSRF_TOKEN: ${{ secrets.RQ_CSRF_TOKEN }}
  RQ_USERID: ${{ secrets.RQ_USERID }}
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_API_CLIENT_EMAIL: ${{ secrets.GOOGLE_API_CLIENT_EMAIL }}
  GOOGLE_API_PRIVATE_KEY: ${{ secrets.GOOGLE_API_PRIVATE_KEY }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sync Garmin CN to Garmin Global
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
      # - run: yarn sync_cn
      - name: Run yarn sync_cn and save the output
        run: |
          # 运行yarn sync_cn任务
          result=$(yarn sync_cn) 
          echo "$result"
          echo "result<<EOF" >> $GITHUB_ENV
          echo "$result" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          # echo "result=$result" >> $GITHUB_ENV // not work
        timeout-minutes: 5
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Save Garmin Session
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Garmin同步状态-Github
          html_body: ${{env.result}}
          to: dongxi8@163.com
          from: GitHub Actions
